packages:
  - examples/*
  - packages/*

catalog:
  '@testing-library/react': 16.3.0
  '@types/node': 24.10.1
  tsup: 8.5.0
  typescript: 5.9.2
  vitest: 4.0.8
  vue: 3.5.24
  zod: 4.1.12

catalogs:
  react:
    '@types/react': 19.2.0
    '@types/react-dom': 19.2.0
    react: 19.2.0
    react-dom: 19.2.0
